config/routes.rb
Kiosku::Application.routes.draw do
  match '/editphoto', to: 'users#photo'
  match '/change', to: 'users#change'
  resources :sessions, only: [:new, :create, :destroy]
  match '/signup', to: 'users#new'
  match '/signin',   to: 'sessions#new'
  match '/signout',  to: 'sessions#destroy', via: :delete
  resources :users

  resources :locations

  root :to => 'welcome#index'

end

app/models/location.rb
class Location < ActiveRecord::Base
  acts_as_gmappable
  attr_accessible :gmaps, :jalan, :kota, :latitude, :longitude, :nama, :provinsi, :photo
  geocoded_by :address, :units=> :km
  after_validation :geocode
  
  has_attached_file :photo,:styles => { :small => "150x150>" }
  def address
    [jalan,kota,provinsi].compact.join(',')
  end
  def gmaps4rails_address
  "#{jalan}, #{kota}, #{provinsi}"
end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  attr_accessible :alamat, :email,
   :ingat_aku, :kota, :nama, :password, :password_confirmation, :provinsi,:photo
   
   has_attached_file :photo,:styles => { :small => "150x150>" }
    
   before_save {|member| member.email=email.downcase}
  before_save :create_ingat_aku
  validates :password, presence: true, length: {minimum: 6}, if: :haruskah_validasi?
  validates :password_confirmation, presence: true, if: :haruskah_validasi?
  EMAIL_VALID = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: {with: EMAIL_VALID}, uniqueness: {case_sensitive: false}  
  has_attached_file :photo, styles: { small: "150x150", thumb: "130x130" }
  
  def self.pelanggan(date)
    where("admin!='t' and date(created_at) = ?",date).count(:id)
  end
  
  private
  def haruskah_validasi?
       new_record?
    end
    def create_ingat_aku
      self.ingat_aku = SecureRandom.urlsafe_base64
    end
    
    def signed_in_user
      redirect_to signin_path, notice: "Please sign in." unless signed_in?
    end
    
    def beneran_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
    @json=@locations.to_gmaps4rails

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @locations }
    end
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    if signed_in?
      @kol=Location.near("#{user_sekarang.alamat},#{user_sekarang.kota},#{user_sekarang.provinsi}",10,order: :distance)
    end
    @location = Location.find(params[:id])
    
    @json=@location.to_gmaps4rails

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/new
  # GET /locations/new.json
  def new
    @location = Location.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/1/edit
  def edit
    @location = Location.find(params[:id])
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(params[:location])

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render json: @location, status: :created, location: @location }
      else
        format.html { render action: "new" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /locations/1
  # PUT /locations/1.json
  def update
    @location = Location.find(params[:id])

    respond_to do |format|
      if @location.update_attributes(params[:location])
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location = Location.find(params[:id])
    @location.destroy

    respond_to do |format|
      format.html { redirect_to locations_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    
  end
  
  def create
    user = User.find_by_email(params[:sessions][:email])
    if user && user.authenticate(params[:sessions][:password])
      #sign in  berhasil
      sign_in user
      redirect_to root_path
    else
      #sig in gagal
      redirect_to signin_path, notice: 'email/password salah'
    end
  end
  def destroy
    sign_out    
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  protect_from_forgery :except => [:update, :delete, :create]
  def photo
    render 'editphoto'
  end
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        sign_in @user
        format.html { redirect_to root_path, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
    end
   

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    if signed_in?
    @locations = Location.near("#{user_sekarang.alamat},#{user_sekarang.kota},#{user_sekarang.provinsi}",10,order: :distance)
     #@locations=Location.all
    else
      @locations=Location.all.to_gmaps4rails
    end
    render 'index'
  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    cookies.permanent[:ingat_aku] = user.ingat_aku
    self.user_sekarang = user
  end
  
  def signed_in?
    !user_sekarang.nil?
  end
  
  def user_sekarang=(user)
        @user_sekarang = user
  end
  
  def user_sekarang
    @user_sekarang ||= User.find_by_ingat_aku(cookies[:ingat_aku])
  end
  
  def sign_out
    user_sekarang = nil
    cookies.delete(:ingat_aku)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_shim.html.erb
<!-- [ifltIE9] -->
<scriptsrc="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<!-- [endif] -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kiosku</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application", :media=>"all" %>
  <%= stylesheet_link_tag 'gmaps4rails' %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
<header>
	<div class="navbar">
		<div class="navbar-inner">
			<b class="brand">Kiosku</b>
			<ul class="nav">
				<li class="active"><%= link_to "Home", root_path%></li>
				<%if signed_in?%>
				
					<li class="dropdown offset11 ">
						<a class="dropdown-toggle" data-toggle="dropdown"><%=user_sekarang.nama%>
							<b class="caret"></b>
						</a>
						<ul class="dropdown-menu">
							<li><a href="#">Action</a></li>
							<li><a href="#">Another action</a></li>
							<li><a href="#"><%= link_to "Edit Profile", edit_user_path(user_sekarang) %></a></li>
							<li class="divider"></li>
							<li><a href="#"><%= link_to "Sign out", signout_path, method: "delete" %></a></li>										
						
					</li>
					
				</ul>
				
				<%else%>
				<li class="active offset11"><%= link_to "Sign In", signin_path%></li>
				<%end%>
				<li class="active"></li>
			</ul>
		</div>
	</div>
</header>
<%= yield %>
<%= yield :scripts %>
</body>
</html>

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nama %><br />
    <%= f.text_field :nama %>
  </div>
  <div class="field">
    <%= f.label :jalan %><br />
    <%= f.text_field :jalan %>
  </div>
  <div class="field">
    <%= f.label :kota %><br />
    <%= f.text_field :kota %>
  </div>
  <div class="field">
    <%= f.label :provinsi %><br />
    <%= f.text_field :provinsi %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :gmaps %><br />
    <%= f.check_box :gmaps %>
  </div>
  <div class="field">
  	<%= f.file_field :photo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<h1>Listing locations</h1>

<table>
  <tr>
    <th>Nama</th>
    <th>Jalan</th>
    <th>Kota</th>
    <th>Provinsi</th>
    <th>Latitude</th>
    <th>Longitude</th>
    <th>Gmaps</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @locations.each do |location| %>
  <tr>
    <td><%= location.nama %></td>
    <td><%= location.jalan %></td>
    <td><%= location.kota %></td>
    <td><%= location.provinsi %></td>
    <td><%= location.latitude %></td>
    <td><%= location.longitude %></td>
    <td><%= location.gmaps %></td>
    <td><%= link_to 'Show', location %></td>
    <td><%= link_to 'Edit', edit_location_path(location) %></td>
    <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Location', new_location_path %>
<%= gmaps4rails(@json) %>

app/views/locations/new.html.erb
<h1>New location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nama:</b>
  <%= @location.nama %>
</p>

<p>
  <b>Jalan:</b>
  <%= @location.jalan %>
</p>

<p>
  <b>Kota:</b>
  <%= @location.kota %>
</p>

<p>
  <b>Provinsi:</b>
  <%= @location.provinsi %>
</p>

<p>
  <b>Latitude:</b>
  <%= @location.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @location.longitude %>
</p>

<p>
  <b>Gmaps:</b>
  <%= @location.gmaps %>
</p>
<%if signed_in?%>
<p>
	<%@kol.each do |f|%>
	<%if f.id==@location.id%>
		Jarak dari tempat anda : <%=f.distance.round(3)%> km
	<%end%>
	<%end%>
</p>
<h2>Tempat Terdekat Lainnya : </h2>
<p>
	<%@kol.each do |f|%>
	<%if f.id != @location.id%>
	<p><%=link_to f.nama, f%>(<%=f.distance.round(3)%> km)</p>
	<%end%>
	<%end%>
</p>
<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>
<%= gmaps(markers: {data: @json}, map_options: {auto_adjust: true, auto_zoom: false, zoom:19},:direction=>{
 		:data => {:from=>"#{user_sekarang.alamat},#{user_sekarang.kota},#{user_sekarang.provinsi}", :to=>"#{@location.jalan},#{@location.kota},#{@location.provinsi}"}}
 		) %>
 <%else%>
 <%= gmaps(markers: {data: @json}, map_options: {auto_adjust: true, auto_zoom: false, zoom:15}) %>
<%end%>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nama %><br />
    <%= f.text_field :nama %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password%><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/editphoto.html.erb
<%=image_tag user_sekarang.photo%>
<%= form_for user_sekarang, :html => { :multipart=> true } do |f| %>
<div class="field">
  	<%= f.file_field :photo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Nama</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.nama %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nama:</b>
  <%= @user.nama %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Password digest:</b>
  <%= @user.password_digest %>
</p>

<p>
  <b>Alamat:</b>
  <%= @user.alamat %>
</p>

<p>
  <b>Kota:</b>
  <%= @user.kota %>
</p>

<p>
  <b>Provinsi:</b>
  <%= @user.provinsi %>
</p>

<p>
  <b>Ingat aku:</b>
  <%= @user.ingat_aku %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/index.html.erb
<%if signed_in?%>
<div class="navbar-form text-center">
<%= form_for user_sekarang, class:"navbar-form text-center" do |f| %>
    <%= f.text_field :alamat, placeholder: 'alamat', class:"span3", id:"fname" %>

    <%= f.text_field :kota, placeholder: 'kota' , class:"span3", id:"fname"%>

    <%= f.text_field :provinsi, placeholder: 'provinsi' , class:"span3", id:"fname"%>

    <%= f.submit 'update lokasi' ,class:"btn"%>

<% end %>
</div>

<div class="row-fluid" style="margin-left: 40%;margin-right: 40%;">
<%@locations.each do|f|%>

<div>
<h3><%=f.nama%></h3>
<div class="row">
<div class="span2"><%=image_tag f.photo(:small)%></div>
<div class="span3">
	<p>Jarak : <%=f.distance.round(3)%> km</p>
	<p><%=f.jalan%>,<%=f.kota%></p>
	<p><%=link_to "view", f, class:"btn"%></p>
</div>
</div>
</div>
<%end%>
</div>

<%else%>
<h1 style="text-align: center;">SELAMAT DATANG</h1>
<%= gmaps(markers: {data: @locations}, map_options: {auto_adjust: true, auto_zoom: true, zoom:3}) %>
<p style="margin-left: 5%;">Kiosku membantu anda mencari lokasi penjualan tiket kereta api, tiket peswawat, 
	tiket bus, tempat pengiriman jasa paket, dan jasa travel di seluruh Indonesia. Kami juga membantu mencari
	lokasi-lokasi tersebut berdasarkan tempat terdekat anda saat ini dan tempat yang anda inginkan. 
	Ayo segera daftar untuk dapat menikmati layanan kami!</p>
	<p  style="text-align: center;"><%=link_to "Sign Up", signup_path, class:"btn"%></p>
<%end%>